### ISSUE TITLE
Firrtl raises java.lang.AssertionError only when --no-dce option is added

### ISSUE THREAD

**Issue by Soya-Onishi** [freechipsproject/firrtl#1214]
**Type of issue**: bug report

**What is the current behavior?**
I'm from chisel-users mailing list and I was encouraged to post this issue(that mail is [here](https://groups.google.com/forum/#!topic/chisel-users/JIq91Ke3TnU)).

If I use `--no-dce` option, firrtl raises `java.lang.AssertionError` exception when trying below sample code to elaborate(stacktrace is in Other Information).
```
circuit Stage :
  module Stage :
    input CLK : Clock
    input RST : UInt<1>
  
    reg stage0 : { active : UInt<1>, params : { arg : UInt<8>}}, CLK with :
      reset => (UInt<1>("h0"), stage0)      
    stage0 is invalid
      
    when stage0.active :
      skip

    when RST :
      stage0.active <= UInt<1>("h0")
    else :
      when stage0.active :
        stage0.active <= UInt<1>("h0")
```
And fixed version works correctly (at least, there is no exception).
```
circuit Stage :
  module Stage :
    input CLK : Clock
    input RST : UInt<1>

    wire TMP_0: { active : UInt<1>, params : { arg : UInt<8>}}
    TMP_0 is invalid
    TMP_0.active <= UInt<8>(0)
    
    reg stage0 : { active : UInt<1>, params : { arg : UInt<8>}}, CLK with :
      reset => (RST, TMP_0)

    when stage0.active :
      skip

    when stage0.active :
      stage0.active <= UInt<1>("h0")
```
To be honest, I don't know whether this is a bug or not. 
This may be expected behavior.
However, I feel weird that it happens only when `--no-dce` option is added.

**What is the expected behavior?**
I want firrtl to cause error regardless there is `--no-dce` or not.
And also, If could, showing only error message instead of exception with stack trace.

**Please tell us about your environment:**
    - version: `1.2.0`
    - OS: `Linux soya 5.0.0-32-generic #34~18.04.2-Ubuntu SMP Thu Oct 10 10:36:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

**Impact**: unknown

**Other information** 
stack trace is here.

```
Exception in thread "main" java.lang.AssertionError: assertion failed: Error! Synchronous reset should have been removed!
	at scala.Predef$.assert(Predef.scala:223)
	at firrtl.VerilogEmitter$VerilogRender.regUpdate(Emitter.scala:568)
	at firrtl.VerilogEmitter$VerilogRender.build_streams(Emitter.scala:724)
	at firrtl.VerilogEmitter$VerilogRender.$anonfun$build_streams$1(Emitter.scala:715)
	at firrtl.VerilogEmitter$VerilogRender.$anonfun$build_streams$1$adapted(Emitter.scala:715)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at firrtl.ir.Block.foreachStmt(IR.scala:375)
	at firrtl.traversals.Foreachers$StmtForMagnet$$anon$1.foreach(Foreachers.scala:18)
	at firrtl.traversals.Foreachers$StmtForeach$.foreach$extension(Foreachers.scala:35)
	at firrtl.VerilogEmitter$VerilogRender.build_streams(Emitter.scala:715)
	at firrtl.VerilogEmitter$VerilogRender.$anonfun$build_streams$1(Emitter.scala:715)
	at firrtl.VerilogEmitter$VerilogRender.$anonfun$build_streams$1$adapted(Emitter.scala:715)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at firrtl.ir.Block.foreachStmt(IR.scala:375)
	at firrtl.traversals.Foreachers$StmtForMagnet$$anon$1.foreach(Foreachers.scala:18)
	at firrtl.traversals.Foreachers$StmtForeach$.foreach$extension(Foreachers.scala:35)
	at firrtl.VerilogEmitter$VerilogRender.build_streams(Emitter.scala:715)
	at firrtl.VerilogEmitter$VerilogRender.$anonfun$build_streams$1(Emitter.scala:715)
	at firrtl.VerilogEmitter$VerilogRender.$anonfun$build_streams$1$adapted(Emitter.scala:715)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at firrtl.ir.Block.foreachStmt(IR.scala:375)
	at firrtl.traversals.Foreachers$StmtForMagnet$$anon$1.foreach(Foreachers.scala:18)
	at firrtl.traversals.Foreachers$StmtForeach$.foreach$extension(Foreachers.scala:35)
	at firrtl.VerilogEmitter$VerilogRender.build_streams(Emitter.scala:715)
	at firrtl.VerilogEmitter$VerilogRender.emit_verilog(Emitter.scala:922)
	at firrtl.VerilogEmitter.$anonfun$emit$3(Emitter.scala:974)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at firrtl.VerilogEmitter.emit(Emitter.scala:968)
	at firrtl.VerilogEmitter.$anonfun$execute$3(Emitter.scala:983)
	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:245)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:245)
	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:242)
	at scala.collection.immutable.List.flatMap(List.scala:355)
	at firrtl.VerilogEmitter.execute(Emitter.scala:980)
	at firrtl.Transform.$anonfun$runTransform$2(Compiler.scala:216)
	at firrtl.Utils$.time(Utils.scala:169)
	at firrtl.Transform.runTransform(Compiler.scala:216)
	at firrtl.Compiler.$anonfun$compile$2(Compiler.scala:480)
	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
	at scala.collection.immutable.List.foldLeft(List.scala:89)
	at firrtl.Compiler.$anonfun$compile$1(Compiler.scala:478)
	at firrtl.Utils$.time(Utils.scala:169)
	at firrtl.Compiler.compile(Compiler.scala:478)
	at firrtl.Compiler.compile$(Compiler.scala:474)
	at firrtl.VerilogCompiler.compile(LoweringCompilers.scala:164)
	at firrtl.stage.phases.Compiler.f$1(Compiler.scala:91)
	at firrtl.stage.phases.Compiler.$anonfun$internalTransform$2(Compiler.scala:95)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at scala.collection.TraversableLike.map(TraversableLike.scala:238)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
	at firrtl.stage.phases.Compiler.internalTransform(Compiler.scala:95)
	at firrtl.stage.phases.Compiler.internalTransform(Compiler.scala:45)
	at firrtl.options.Translator.transform(Phase.scala:140)
	at firrtl.options.Translator.transform$(Phase.scala:140)
	at firrtl.stage.phases.Compiler.transform(Compiler.scala:45)
	at firrtl.options.phases.DeletedWrapper.internalTransform(DeletedWrapper.scala:32)
	at firrtl.options.phases.DeletedWrapper.internalTransform(DeletedWrapper.scala:15)
	at firrtl.options.Translator.transform(Phase.scala:140)
	at firrtl.options.Translator.transform$(Phase.scala:140)
	at firrtl.options.phases.DeletedWrapper.transform(DeletedWrapper.scala:15)
	at firrtl.stage.FirrtlStage.$anonfun$run$1(FirrtlStage.scala:28)
	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
	at scala.collection.immutable.List.foldLeft(List.scala:89)
	at firrtl.stage.FirrtlStage.run(FirrtlStage.scala:28)
	at firrtl.options.Stage$$anon$1.transform(Stage.scala:43)
	at firrtl.options.Stage$$anon$1.transform(Stage.scala:43)
	at firrtl.options.phases.DeletedWrapper.internalTransform(DeletedWrapper.scala:32)
	at firrtl.options.phases.DeletedWrapper.internalTransform(DeletedWrapper.scala:15)
	at firrtl.options.Translator.transform(Phase.scala:140)
	at firrtl.options.Translator.transform$(Phase.scala:140)
	at firrtl.options.phases.DeletedWrapper.transform(DeletedWrapper.scala:15)
	at firrtl.options.Stage.$anonfun$transform$5(Stage.scala:46)
	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
	at scala.collection.immutable.List.foldLeft(List.scala:89)
	at firrtl.options.Stage.$anonfun$transform$3(Stage.scala:46)
	at logger.Logger$.$anonfun$makeScope$2(Logger.scala:168)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at logger.Logger$.makeScope(Logger.scala:166)
	at firrtl.options.Stage.transform(Stage.scala:46)
	at firrtl.options.Stage.execute(Stage.scala:57)
	at firrtl.options.StageMain.main(Stage.scala:70)
	at firrtl.stage.FirrtlMain.main(FirrtlStage.scala)
```

**Comment by albert-magyar** [comment]
Thanks for bringing this issue to our attention. This is in fact a bug!

It turns out that another optimization that calls DCE in a tight loop was generating legal FIRRTL that violated the assumptions of the emitter. This was normally masked by the fact that DCE would immediately remove the offending code.
