### ISSUE TITLE
RemoveAccesses exception when indexing 0-element vec

### ISSUE THREAD

**Issue by aswaterman** [freechipsproject/firrtl#230]
The following circuit causes RemoveAccesses to fail:

```
circuit bar :
  module bar :
    output foo : UInt<1>[0]
    foo[UInt(0)] <= UInt(0)
```

I think this should be legal and the behavior should match the non-power-of-2 out-of-bounds case, e.g. indexing a 5-element array with dynamic index 7.

```
Exception in thread "main" java.lang.IndexOutOfBoundsException: 0
at scala.collection.mutable.ResizableArray$class.apply(ResizableArray.scala:43)
at scala.collection.mutable.ArrayBuffer.apply(ArrayBuffer.scala:48)
at firrtl.passes.RemoveAccesses$.removeFemale$1(RemoveAccesses.scala:114)
at firrtl.passes.RemoveAccesses$.firrtl$passes$RemoveAccesses$$onStmt$1(RemoveAccesses.scala:145)
at firrtl.passes.RemoveAccesses$$anonfun$4.apply(RemoveAccesses.scala:146)
at firrtl.passes.RemoveAccesses$$anonfun$4.apply(RemoveAccesses.scala:146)
at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
at scala.collection.AbstractTraversable.map(Traversable.scala:104)
at firrtl.Mappers$StmtMagnet$$anon$4.map(Mappers.scala:44)
at firrtl.Mappers$StmtMap.map(Mappers.scala:95)
at firrtl.passes.RemoveAccesses$.firrtl$passes$RemoveAccesses$$onStmt$1(RemoveAccesses.scala:146)
at firrtl.passes.RemoveAccesses$$anonfun$4.apply(RemoveAccesses.scala:146)
at firrtl.passes.RemoveAccesses$$anonfun$4.apply(RemoveAccesses.scala:146)
at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
at scala.collection.AbstractTraversable.map(Traversable.scala:104)
at firrtl.Mappers$StmtMagnet$$anon$4.map(Mappers.scala:44)
at firrtl.Mappers$StmtMap.map(Mappers.scala:95)
at firrtl.passes.RemoveAccesses$.firrtl$passes$RemoveAccesses$$onStmt$1(RemoveAccesses.scala:146)
at firrtl.passes.RemoveAccesses$.firrtl$passes$RemoveAccesses$$remove_m$1(RemoveAccesses.scala:151)
at firrtl.passes.RemoveAccesses$$anonfun$6.apply(RemoveAccesses.scala:156)
at firrtl.passes.RemoveAccesses$$anonfun$6.apply(RemoveAccesses.scala:154)
at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
at scala.collection.AbstractTraversable.map(Traversable.scala:104)
at firrtl.passes.RemoveAccesses$.run(RemoveAccesses.scala:154)
at firrtl.SimpleRun$$anonfun$1$$anonfun$2.apply(LoweringCompilers.scala:48)
at firrtl.SimpleRun$$anonfun$1$$anonfun$2.apply(LoweringCompilers.scala:48)
at firrtl.Utils$.time(Utils.scala:57)
at firrtl.SimpleRun$$anonfun$1.apply(LoweringCompilers.scala:48)
at firrtl.SimpleRun$$anonfun$1.apply(LoweringCompilers.scala:46)
at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
at scala.collection.immutable.List.foldLeft(List.scala:84)
at firrtl.SimpleRun$class.run(LoweringCompilers.scala:45)
at firrtl.HighFirrtlToMiddleFirrtl.run(LoweringCompilers.scala:104)
at firrtl.HighFirrtlToMiddleFirrtl.execute(LoweringCompilers.scala:117)
at firrtl.Compiler$$anonfun$compile$1.apply(Compiler.scala:71)
at firrtl.Compiler$$anonfun$compile$1.apply(Compiler.scala:70)
at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
at scala.collection.immutable.List.foldLeft(List.scala:84)
at firrtl.Compiler$class.compile(Compiler.scala:70)
at firrtl.VerilogCompiler.compile(LoweringCompilers.scala:198)
at firrtl.Driver$.compile(Driver.scala:60)
at firrtl.Driver$.run(Driver.scala:173)
at firrtl.Driver$.main(Driver.scala:96)
at firrtl.Driver.main(Driver.scala)
```

**Comment by azidar** [comment]
What would the expanded form of ```output foo: UInt[0]``` be?

**Comment by aswaterman** [comment]
No output at all would be consistent with the current flattening scheme for vectors.  I believe that part is already correctly implemented.

**Comment by ekiwi** [comment]
Just ran the example from Andrew with the latest `master` branch of `firrtl`:

```
Exception in thread "main" firrtl.passes.CheckTypes$IndexTooLarge: : [module bar]  Index with value 0 is too large.
```

This seems to make sense since the Vec has zero elements and thus there is no element zero.

**Comment by azidar** [comment]
This example is still broken:

```
circuit bar :
  module bar :
    output foo : UInt<1>[0]
    input x: UInt<1>
    foo[x] <= UInt(0)
```

with stack trace:

```
Exception in thread "main" firrtl.FirrtlInternalException: Internal Error! Please file an issue at https://github.com/ucb-bar/firrtl/issues
	at firrtl.Utils$.error(Utils.scala:431)
	at firrtl.Utils$.throwInternalError(Utils.scala:166)
	at firrtl.stage.FirrtlStage.run(FirrtlStage.scala:35)
	at firrtl.options.Stage$$anon$1.transform(Stage.scala:43)
	at firrtl.options.Stage$$anon$1.transform(Stage.scala:43)
	at firrtl.options.phases.DeletedWrapper.internalTransform(DeletedWrapper.scala:32)
	at firrtl.options.phases.DeletedWrapper.internalTransform(DeletedWrapper.scala:15)
	at firrtl.options.Translator.transform(Phase.scala:140)
	at firrtl.options.Translator.transform$(Phase.scala:140)
	at firrtl.options.phases.DeletedWrapper.transform(DeletedWrapper.scala:15)
	at firrtl.options.Stage.$anonfun$transform$5(Stage.scala:46)
	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
	at scala.collection.immutable.List.foldLeft(List.scala:89)
	at firrtl.options.Stage.$anonfun$transform$3(Stage.scala:46)
	at logger.Logger$.$anonfun$makeScope$2(Logger.scala:168)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at logger.Logger$.makeScope(Logger.scala:166)
	at firrtl.options.Stage.transform(Stage.scala:46)
	at firrtl.options.Stage.execute(Stage.scala:57)
	at firrtl.options.StageMain.main(Stage.scala:70)
	at firrtl.stage.FirrtlMain.main(FirrtlStage.scala)
Caused by: java.lang.UnsupportedOperationException: empty.head
	at scala.collection.immutable.Vector.head(Vector.scala:189)
	at firrtl.passes.RemoveAccesses.removeFemale$1(RemoveAccesses.scala:121)
	at firrtl.passes.RemoveAccesses.onStmt$1(RemoveAccesses.scala:154)
	at firrtl.passes.RemoveAccesses.$anonfun$run$10(RemoveAccesses.scala:155)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.TraversableLike.map(TraversableLike.scala:238)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
	at scala.collection.immutable.List.map(List.scala:298)
	at firrtl.ir.Block.mapStmt(IR.scala:397)
```

**Comment by lijinpei** [comment]
May I ask what's the expected expanded form of this example:
```fir
circuit bar :
  module bar :
    output foo : UInt<1>[0]
    input x: UInt<1>
    foo[x] <= UInt(0)
```
A. Compile time error message(but not compiler throw exception)
B. effectively this(because vector index automatically wrap arounds and zero-length dead vectors are eliminated):
```fir
circuit bar :
  module bar :
    input x: UInt<1>
```
