### ISSUE TITLE
Can't read in firrtl-generated .lo.fir file for default rocketchip build.

### ISSUE THREAD

**Issue by stevenmburns** [freechipsproject/firrtl#608]
The following sequence of two firrtl runs bombs with a syntax error.

````
(general) smburns@smburns-VirtualBox:~/rocketchipfirrtl$ firrtl -X low -tn rocketchip.DefaultConfig
Total FIRRTL Compile Time: 76175.6 ms
(general) smburns@smburns-VirtualBox:~/rocketchipfirrtl$ mv rocketchip.DefaultConfig.lo.fir rocketchip.DefaultConfig.lo1.fir 
(general) smburns@smburns-VirtualBox:~/rocketchipfirrtl$ firrtl -X low -tn rocketchip.DefaultConfig -i rocketchip.DefaultConfig.lo1.fir
line 4205:23 no viable alternative at input 'parameterFORMAT=tilelink_timeout'
line 4205:40 token recognition error at: '%'
Exception in thread "main" firrtl.ParserException: 1 syntax error(s) detected
	at firrtl.Parser$$anonfun$1.apply(Parser.scala:45)
	at firrtl.Parser$$anonfun$1.apply(Parser.scala:29)
	at firrtl.Utils$.time(Utils.scala:135)
	at firrtl.Parser$.parse(Parser.scala:29)
	at firrtl.Driver$$anonfun$execute$1.apply(Driver.scala:160)
	at firrtl.Driver$$anonfun$execute$1.apply(Driver.scala:129)
	at logger.Logger$$anonfun$makeScope$1.apply(Logger.scala:129)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at logger.Logger$.makeScope(Logger.scala:127)
	at firrtl.Driver$.execute(Driver.scala:129)
	at firrtl.Driver$.execute(Driver.scala:216)
	at firrtl.Driver$.main(Driver.scala:232)
	at firrtl.Driver.main(Driver.scala)
````

It seems that a parameter is not being correctly quoted.
Adding the quotes below corrects the issue.
````
  extmodule plusarg_reader : @[:@2499.2]
    output out : UInt<32> @[:@2500.4]
  
    defname = plusarg_reader
    parameter FORMAT = "tilelink_timeout=%d"
    parameter DEFAULT = 0

  module TLMonitor : @[:@2506.2]
````

**Comment by albert-magyar** [comment]
Fixed by #675
