### ISSUE TITLE
Mems with 0-width entries can't be assigned to

### ISSUE THREAD

**Issue by grebe** [freechipsproject/firrtl#666]
The following firrtl crashes the compiler:
```
circuit BadMem :
  module BadMem :
    input clk  : Clock
    input addr : UInt<4>
    input in   : {0: UInt<10>, 1: UInt<0>}

    cmem ram : {0: UInt<10>, 1: UInt<0>}[16]
    infer mport ramin = ram[addr], clk

    ramin.0 <= in.0
    ramin.1 <= in.1
```

I get the error `java.util.NoSuchElementException: key not found: ram_1`. I think this should be legal firrtl.

FWIW, if you switch in to an output and flip the assignments, everything works fine.

**Comment by ducky64** [comment]
Also getting this bug when attempting to instantiate a Queue of 0-width UInt

Error:
```
[info]   java.util.NoSuchElementException: key not found: ram
[info]   at scala.collection.MapLike$class.default(MapLike.scala:228)
[info]   at scala.collection.AbstractMap.default(Map.scala:59)
[info]   at scala.collection.MapLike$class.apply(MapLike.scala:141)
[info]   at scala.collection.AbstractMap.apply(Map.scala:59)
[info]   at firrtl.passes.InferTypes$.firrtl$passes$InferTypes$$infer_types_e$1(InferTypes.scala:27)
[info]   at firrtl.passes.InferTypes$$anonfun$2.apply(InferTypes.scala:26)
[info]   at firrtl.passes.InferTypes$$anonfun$2.apply(InferTypes.scala:26)
[info]   at firrtl.WSubField.mapExpr(WIR.scala:42)
[info]   at firrtl.Mappers$ExprMagnet$$anon$5.map(Mappers.scala:39)
[info]   at firrtl.Mappers$ExprMap$.map$extension(Mappers.scala:49)
[info]   ...
```
