### ISSUE TITLE
fail when I compiled 

### ISSUE THREAD

**Issue by esolera** [freechipsproject/firrtl#677]
I´m clone the proyect and tried to run this comand
              
                   sbt compile 

And I have this error:

           [info] Loading project definition from 
           /mnt/vol_NFS_Zener/WD_ESPEC/RISCV/riscv_gabo/firrtl/project
           [info] Updating {file:/mnt/vol_NFS_Zener/WD_ESPEC/RISCV/riscv_gabo/firrtl/project/}firrtl-build...
           [info] Resolving org.fusesource.jansi#jansi;1.4 ...
           [info] Done updating.
           [warn] Found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
           [warn] 
           [warn]  * xml-apis:xml-apis:1.3.04 is selected over 2.0.2
           [warn]      +- org.apache.xmlgraphics:batik-script:1.8            (depends on 1.3.04)
           [warn]      +- org.apache.xmlgraphics:batik-anim:1.8              (depends on 1.3.04)
           [warn]      +- org.apache.xmlgraphics:batik-transcoder:1.8        (depends on 1.3.04)
           [warn]      +- org.apache.xmlgraphics:batik-bridge:1.8            (depends on 1.3.04)
           [warn]      +- org.apache.xmlgraphics:batik-svg-dom:1.8           (depends on 1.3.04)
           [warn]      +- org.apache.xmlgraphics:batik-parser:1.8            (depends on 1.3.04)
           [warn]      +- org.apache.xmlgraphics:batik-dom:1.8               (depends on 1.3.04)
           [warn]      +- org.apache.xmlgraphics:batik-css:1.8               (depends on 1.3.04)
           [warn]      +- org.apache.xmlgraphics:batik-ext:1.8               (depends on 1.3.04)
           [warn]      +- org.apache.xmlgraphics:batik-extension:1.8         (depends on 1.3.04)
           [warn]      +- org.apache.xmlgraphics:batik-svggen:1.8            (depends on 1.3.04)
           [warn]      +- xalan:xalan:2.7.0                                  (depends on 2.0.2)
           [warn] 
           [warn] Run 'evicted' to see detailed eviction warnings
           usage: git ls-remote [--heads] [--tags]  [-u <exec> | --upload-pack <exec>] <repository> <refs>...
           java.util.NoSuchElementException: head of empty stream
                   at scala.collection.immutable.Stream$Empty$.head(Stream.scala:1028)
                   at scala.collection.immutable.Stream$Empty$.head(Stream.scala:1026)
                   at com.typesafe.sbt.SbtGit$$anonfun$buildSettings$11.apply(SbtGit.scala:138)
                   at com.typesafe.sbt.SbtGit$$anonfun$buildSettings$11.apply(SbtGit.scala:122)
                   at sbt.Init$Value$$anonfun$apply$13.apply(Settings.scala:609)
                  at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$constant$1.apply(INode.scala:163)
                   at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$constant$1.apply(INode.scala:163)
                   at sbt.EvaluateSettings$MixedNode.evaluate0(INode.scala:175)
                   at sbt.EvaluateSettings$INode.evaluate(INode.scala:135)
                   at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$submitEvaluate$1.apply$mcV$sp(INode.scala:69)
                   at sbt.EvaluateSettings.sbt$EvaluateSettings$$run0(INode.scala:78)
                   at sbt.EvaluateSettings$$anon$3.run(INode.scala:74)
                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
                  at java.lang.Thread.run(Thread.java:748)
                [error] java.util.NoSuchElementException: head of empty stream
                [error] Use 'last' for the full log.
                Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? q

PD:I´m using centos.

**Comment by jackkoenig** [comment]
See solution in https://github.com/freechipsproject/rocket-chip/issues/1041
