### ISSUE TITLE
Unexpected/confusing MatchError in LowerTypes

### ISSUE THREAD

**Issue by edwardcwang** [freechipsproject/firrtl#797]
Consider the following invocation of LowerTypes:

```scala
class MidToLowFirrtlCompiler extends firrtl.Compiler {
  def emitter = new firrtl.LowFirrtlEmitter
  def transforms: Seq[firrtl.Transform] = firrtl.CompilerUtils.getLoweringTransforms(firrtl.MidForm, firrtl.LowForm)
}

object test extends App {
  val testContents =
    """
      |circuit IntXbar : @[:ee194.EE194RocketConfig.fir@2.0]
      |  module IntXbar : @[:ee194.EE194RocketConfig.fir@3.2]
      |    input clock : Clock @[:ee194.EE194RocketConfig.fir@4.4]
      |    input reset : UInt<1> @[:ee194.EE194RocketConfig.fir@5.4]
      |    output auto : { flip int_in : UInt<1>[1], int_out : UInt<1>[1]} @[:ee194.EE194RocketConfig.fir@6.4]
      |
      |    wire _T_7 : UInt<1>[1] @[Nodes.scala 329:76:ee194.EE194RocketConfig.fir@11.4]
      |    wire _T_14 : UInt<1>[1] @[Nodes.scala 328:76:ee194.EE194RocketConfig.fir@13.4]
      |    auto.int_out[0] <= _T_14[0]
      |    _T_7[0] <= auto.int_in[0]
      |    _T_14[0] <= _T_7[0]
    """.stripMargin
  val parsedInput = firrtl.Parser.parse(testContents.split("\n").iterator, firrtl.Parser.UseInfo)
  val state = firrtl.CircuitState(parsedInput, firrtl.MidForm, firrtl.AnnotationSeq(Seq.empty))
  (new MidToLowFirrtlCompiler).compileAndEmit(state)
}
```

This results in a confusing/unexpected MatchError in the LowerTypes pass. It seems like the pass doesn't like something about the expression `auto.int_out[0]`.

```
scala.MatchError: SubIndex(SubField(Reference(auto,UnknownType),int_out,UnknownType),0,UnknownType) (of class firrtl.ir.SubIndex)
  at firrtl.passes.LowerTypes$.lowerTypesExp(LowerTypes.scala:140)
  at firrtl.passes.LowerTypes$$anonfun$lowerTypesStmt$12.apply(LowerTypes.scala:254)
  at firrtl.passes.LowerTypes$$anonfun$lowerTypesStmt$12.apply(LowerTypes.scala:254)
  at firrtl.ir.Connect.mapExpr(IR.scala:300)
  at firrtl.Mappers$StmtMagnet$$anon$2.map(Mappers.scala:19)
  at firrtl.Mappers$StmtMap$.map$extension(Mappers.scala:33)
  at firrtl.passes.LowerTypes$.lowerTypesStmt(LowerTypes.scala:254)
  at firrtl.passes.LowerTypes$$anonfun$1.apply(LowerTypes.scala:164)
  at firrtl.passes.LowerTypes$$anonfun$1.apply(LowerTypes.scala:164)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
  at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
  at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
  at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
  at scala.collection.AbstractTraversable.map(Traversable.scala:104)
  at firrtl.ir.Block.mapStmt(IR.scala:283)
  at firrtl.Mappers$StmtMagnet$$anon$1.map(Mappers.scala:16)
  at firrtl.Mappers$StmtMap$.map$extension(Mappers.scala:33)
  at firrtl.passes.LowerTypes$.lowerTypesStmt(LowerTypes.scala:164)
  at firrtl.passes.LowerTypes$$anonfun$lowerTypes$1.apply(LowerTypes.scala:276)
  at firrtl.passes.LowerTypes$$anonfun$lowerTypes$1.apply(LowerTypes.scala:276)
  at firrtl.ir.Module.mapStmt(IR.scala:540)
  at firrtl.Mappers$ModuleMagnet$$anon$12.map(Mappers.scala:93)
  at firrtl.Mappers$ModuleMap$.map$extension(Mappers.scala:106)
  at firrtl.passes.LowerTypes$.lowerTypes(LowerTypes.scala:276)
  at firrtl.passes.LowerTypes$$anonfun$11.apply(LowerTypes.scala:284)
  at firrtl.passes.LowerTypes$$anonfun$11.apply(LowerTypes.scala:284)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
  at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
  at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
  at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
  at scala.collection.AbstractTraversable.map(Traversable.scala:104)
  at firrtl.passes.LowerTypes$.execute(LowerTypes.scala:284)
  at firrtl.Transform$$anonfun$2.apply(Compiler.scala:257)
  at firrtl.Transform$$anonfun$2.apply(Compiler.scala:257)
  at firrtl.Utils$.time(Utils.scala:182)
  at firrtl.Transform.runTransform(Compiler.scala:257)
  at firrtl.SeqTransformBased$$anonfun$runTransforms$1.apply(Compiler.scala:309)
  at firrtl.SeqTransformBased$$anonfun$runTransforms$1.apply(Compiler.scala:309)
  at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
  at scala.collection.immutable.List.foldLeft(List.scala:84)
  at firrtl.SeqTransformBased$class.runTransforms(Compiler.scala:309)
  at firrtl.SeqTransform.runTransforms(Compiler.scala:313)
  at firrtl.SeqTransform.execute(Compiler.scala:319)
  at firrtl.Transform$$anonfun$2.apply(Compiler.scala:257)
  at firrtl.Transform$$anonfun$2.apply(Compiler.scala:257)
  at firrtl.Utils$.time(Utils.scala:182)
  at firrtl.Transform.runTransform(Compiler.scala:257)
  at firrtl.Compiler$$anonfun$7$$anonfun$apply$8.apply(Compiler.scala:471)
  at firrtl.Compiler$$anonfun$7$$anonfun$apply$8.apply(Compiler.scala:471)
  at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
  at scala.collection.immutable.List.foldLeft(List.scala:84)
  at firrtl.Compiler$$anonfun$7.apply(Compiler.scala:471)
  at firrtl.Compiler$$anonfun$7.apply(Compiler.scala:471)
  at firrtl.Utils$.time(Utils.scala:182)
  at firrtl.Compiler$class.compile(Compiler.scala:470)
  at MidToLowFirrtlCompiler.compile(<console>:11)
  at firrtl.Compiler$class.compileAndEmit(Compiler.scala:455)
  at MidToLowFirrtlCompiler.compileAndEmit(<console>:11)
```

firrtl revision b72b6ebec78343c7ad12cbb51834118e69b1443b

The error is reproducible as far back as 1.0 though.

**Comment by albert-magyar** [comment]
This is basically just a "pass expects WIR but gets IR" bug. The particular issue is that `getLoweringTransforms` only includes `IRToWorkingIR` if the input form is either Chirrtl or High FIRRTL.

This is a flaw that is being resolved with the Dependency API. While #1123 and #1357 may not specifically track this bug, the WIR compatibility is also being explicitly resolved with #1350.
