### ISSUE TITLE
Internal FIRRTL Error 

### ISSUE THREAD

**Issue by maloneymr** [freechipsproject/firrtl#973]
**Type of issue**: bug report

I was trying to write a VGA controller as an exercise. I managed to trigger an internal compiler error in FIRRTL. I don't know if this is legitimately an internal error or if I didn't initialize something, but either way, some guidance would be appreciated.

```
import chisel3._
import chisel3.util.Enum

class Top extends Module {
  val io = IO(new Bundle {
    val led = Output(UInt(16.W))

    val vga_red = Output(UInt(4.W))
    val vga_green = Output(UInt(4.W))
    val vga_blue = Output(UInt(4.W))

    val vga_hs = Output(Bool())
    val vga_vs = Output(Bool())
  })

  val vga = Module(new Vga)
  val vgaClock = Module(new VgaClock);
  val counter = RegInit(UInt(32.W), 0.U)

  vga.io.vgaClock := vgaClock.io.out

  when(vgaClock.io.out) {
    counter := counter + 1.U
  }

  io.led := counter(31, 16)

  io.vga_red := vga.io.red
  io.vga_green := vga.io.green
  io.vga_blue := vga.io.blue
  io.vga_hs := vga.io.hs
  io.vga_vs := vga.io.vs
}

class Vga extends Module {
  val io = IO(new Bundle {
    val vgaClock = Input(Bool())

    val red = Output(UInt(4.W))
    val green = Output(UInt(4.W))
    val blue = Output(UInt(4.W))
    val hs = Output(Bool())
    val vs = Output(Bool())
  })

  val drawMode :: hsMode :: vsMode :: Nil = Enum(3)

  val pixelX = RegInit(UInt(10.W), 0.U)
  val pixelY = RegInit(UInt(10.W), 0.U)
  val mode = RegInit(UInt(2.W), drawMode)
  val sync = RegInit(UInt(8.W), 0.U)

  val height = 640.U
  val width = 480.U

  // in ticks
  val horizontalFrontPorch = 16.U
  val horizontalSync = 128.U
  val horizontalBackPorch = 16.U
  val horizontalBlanking = horizontalFrontPorch + horizontalSync + horizontalBackPorch
  val lineSize = horizontalBlanking

  // in lines
  val verticalFrontPorch = 10.U
  val verticalSync = 2.U
  val verticalBackPorch = 29.U
  val verticalBlanking = verticalFrontPorch + verticalSync + verticalBackPorch

  when(io.vgaClock) {
    when (mode === drawMode) {
      when(pixelX < width) {
        pixelX := pixelX + 1.U
      }.otherwise {
        mode := hsMode
        sync := 0.U
      }
    }.elsewhen(mode === hsMode) {
      when(sync < horizontalBlanking) {
        sync := sync + 1.U
        io.hs := !(
          sync >= horizontalFrontPorch &&
          sync < horizontalBlanking - horizontalBackPorch
        )
      }.elsewhen(pixelY < height) {
        mode := drawMode
        pixelX := 0.U
        pixelY := pixelY + 1.U
      }.otherwise {
        mode := vsMode
        sync := 0.U
      }
    }.otherwise {
      when(sync < verticalBlanking * lineSize) {
        sync := sync + 1.U
      }.otherwise {
        mode := drawMode
        pixelX := 0.U
        pixelY := 0.U
      }
    }
  }

  io.red := 0.U
  io.green := 0.U
  io.blue := 0.U

  io.hs := mode === hsMode && !(sync >= horizontalFrontPorch && sync < horizontalBlanking - horizontalBackPorch)
  io.vs := mode === vsMode && !(sync >= verticalFrontPorch * lineSize && sync < (verticalBlanking - verticalBackPorch) * lineSize)
}

class VgaClock extends Module {
  val io = IO(new Bundle {
    val out = Output(Bool())
  })

  val counter = RegInit(UInt(2.W), 0.U)
  counter := counter + 1.U
  io.out := counter === 0.U
}

class Foo extends Module {
  val io = IO(new Bundle {
    val foo = Output(Bool())
  })

  io.foo := true.B
}

object Main extends App {
    chisel3.Driver.execute(args, () => new Top)
}
```

```
mmaloney@sagerbox:~/projects/chisel-template$ sbt 'runMain Main'
[info] Loading settings from plugins.sbt ...
[info] Loading project definition from /home/mmaloney/projects/chisel-template/project
[info] Loading settings from build.sbt ...
[info] Set current project to chisel-module-template (in build file:/home/mmaloney/projects/chisel-template/)
[info] Compiling 1 Scala source to /home/mmaloney/projects/chisel-template/target/scala-2.11/classes ...
[warn] there were 23 feature warnings; re-run with -feature for details
[warn] one warning found
[info] Done compiling.
[info] Packaging /home/mmaloney/projects/chisel-template/target/scala-2.11/chisel-module-template_2.11-3.1.1.jar ...
[info] Done packaging.
[info] Running Main 
[info] [0.002] Elaborating design...
[info] [0.601] Done elaborating.
[error] (run-main-0) firrtl.FIRRTLException: Internal Error! Please file an issue at https://github.com/ucb-bar/firrtl/issues
[error] firrtl.FIRRTLException: Internal Error! Please file an issue at https://github.com/ucb-bar/firrtl/issues
[error] 	at firrtl.Utils$.error(Utils.scala:396)
[error] 	at firrtl.Utils$.throwInternalError(Utils.scala:177)
[error] 	at firrtl.Driver$$anonfun$execute$1.apply(Driver.scala:237)
[error] 	at firrtl.Driver$$anonfun$execute$1.apply(Driver.scala:209)
[error] 	at logger.Logger$$anonfun$makeScope$1.apply(Logger.scala:138)
[error] 	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
[error] 	at logger.Logger$.makeScope(Logger.scala:136)
[error] 	at firrtl.Driver$.execute(Driver.scala:209)
[error] 	at chisel3.Driver$.execute(Driver.scala:182)
[error] 	at chisel3.Driver$.execute(Driver.scala:202)
[error] 	at Main$.delayedEndpoint$Main$1(Top.scala:130)
[error] 	at Main$delayedInit$body.apply(Top.scala:129)
[error] 	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
[error] 	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
[error] 	at scala.App$$anonfun$main$1.apply(App.scala:76)
[error] 	at scala.App$$anonfun$main$1.apply(App.scala:76)
[error] 	at scala.collection.immutable.List.foreach(List.scala:392)
[error] 	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
[error] 	at scala.App$class.main(App.scala:76)
[error] 	at Main$.main(Top.scala:129)
[error] 	at Main.main(Top.scala)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)
[error] 	at sbt.Run.invokeMain(Run.scala:93)
[error] 	at sbt.Run.run0(Run.scala:87)
[error] 	at sbt.Run.execute$1(Run.scala:65)
[error] 	at sbt.Run.$anonfun$run$4(Run.scala:77)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] 	at sbt.util.InterfaceUtil$$anon$1.get(InterfaceUtil.scala:10)
[error] 	at sbt.TrapExit$App.run(TrapExit.scala:252)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] Caused by: scala.MatchError: WVoid (of class firrtl.WVoid$)
[error] 	at firrtl.passes.InferTypes$.firrtl$passes$InferTypes$$infer_types_e$1(InferTypes.scala:26)
[error] 	at firrtl.passes.InferTypes$$anonfun$2.apply(InferTypes.scala:26)
[error] 	at firrtl.passes.InferTypes$$anonfun$2.apply(InferTypes.scala:26)
[error] 	at firrtl.ir.Mux.mapExpr(IR.scala:143)
[error] 	at firrtl.Mappers$ExprMagnet$$anon$6.map(Mappers.scala:42)
[error] 	at firrtl.Mappers$ExprMap$.map$extension(Mappers.scala:52)
[error] 	at firrtl.passes.InferTypes$.firrtl$passes$InferTypes$$infer_types_e$1(InferTypes.scala:26)
[error] 	at firrtl.passes.InferTypes$$anonfun$4.apply(InferTypes.scala:47)
[error] 	at firrtl.passes.InferTypes$$anonfun$4.apply(InferTypes.scala:47)
[error] 	at firrtl.ir.DefNode.mapExpr(IR.scala:262)
[error] 	at firrtl.Mappers$StmtMagnet$$anon$2.map(Mappers.scala:19)
[error] 	at firrtl.Mappers$StmtMap$.map$extension(Mappers.scala:33)
[error] 	at firrtl.passes.InferTypes$.firrtl$passes$InferTypes$$infer_types_s$1(InferTypes.scala:47)
[error] 	at firrtl.passes.InferTypes$$anonfun$firrtl$passes$InferTypes$$infer_types_s$1$5.apply(InferTypes.scala:59)
[error] 	at firrtl.passes.InferTypes$$anonfun$firrtl$passes$InferTypes$$infer_types_s$1$5.apply(InferTypes.scala:59)
[error] 	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
[error] 	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
[error] 	at scala.collection.immutable.List.foreach(List.scala:392)
[error] 	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
[error] 	at scala.collection.immutable.List.map(List.scala:296)
[error] 	at firrtl.ir.Block.mapStmt(IR.scala:285)
[error] 	at firrtl.Mappers$StmtMagnet$$anon$1.map(Mappers.scala:16)
[error] 	at firrtl.Mappers$StmtMap$.map$extension(Mappers.scala:33)
[error] 	at firrtl.passes.InferTypes$.firrtl$passes$InferTypes$$infer_types_s$1(InferTypes.scala:59)
[error] 	at firrtl.passes.InferTypes$$anonfun$firrtl$passes$InferTypes$$infer_types_s$1$5.apply(InferTypes.scala:59)
[error] 	at firrtl.passes.InferTypes$$anonfun$firrtl$passes$InferTypes$$infer_types_s$1$5.apply(InferTypes.scala:59)
[error] 	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
[error] 	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
[error] 	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
[error] 	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
[error] 	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
[error] 	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
[error] 	at firrtl.ir.Block.mapStmt(IR.scala:285)
[error] 	at firrtl.Mappers$StmtMagnet$$anon$1.map(Mappers.scala:16)
[error] 	at firrtl.Mappers$StmtMap$.map$extension(Mappers.scala:33)
[error] 	at firrtl.passes.InferTypes$.firrtl$passes$InferTypes$$infer_types_s$1(InferTypes.scala:59)
[error] 	at firrtl.passes.InferTypes$$anonfun$firrtl$passes$InferTypes$$infer_types_s$1$5.apply(InferTypes.scala:59)
[error] 	at firrtl.passes.InferTypes$$anonfun$firrtl$passes$InferTypes$$infer_types_s$1$5.apply(InferTypes.scala:59)
[error] 	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
[error] 	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
[error] 	at scala.collection.immutable.List.foreach(List.scala:392)
[error] 	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
[error] 	at scala.collection.immutable.List.map(List.scala:296)
[error] 	at firrtl.ir.Block.mapStmt(IR.scala:285)
[error] 	at firrtl.Mappers$StmtMagnet$$anon$1.map(Mappers.scala:16)
[error] 	at firrtl.Mappers$StmtMap$.map$extension(Mappers.scala:33)
[error] 	at firrtl.passes.InferTypes$.firrtl$passes$InferTypes$$infer_types_s$1(InferTypes.scala:59)
[error] 	at firrtl.passes.InferTypes$$anonfun$firrtl$passes$InferTypes$$infer_types_s$1$5.apply(InferTypes.scala:59)
[error] 	at firrtl.passes.InferTypes$$anonfun$firrtl$passes$InferTypes$$infer_types_s$1$5.apply(InferTypes.scala:59)
[error] 	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
[error] 	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
[error] 	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
[error] 	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
[error] 	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
[error] 	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
[error] 	at firrtl.ir.Block.mapStmt(IR.scala:285)
[error] 	at firrtl.Mappers$StmtMagnet$$anon$1.map(Mappers.scala:16)
[error] 	at firrtl.Mappers$StmtMap$.map$extension(Mappers.scala:33)
[error] 	at firrtl.passes.InferTypes$.firrtl$passes$InferTypes$$infer_types_s$1(InferTypes.scala:59)
[error] 	at firrtl.passes.InferTypes$$anonfun$firrtl$passes$InferTypes$$infer_types_s$1$5.apply(InferTypes.scala:59)
[error] 	at firrtl.passes.InferTypes$$anonfun$firrtl$passes$InferTypes$$infer_types_s$1$5.apply(InferTypes.scala:59)
[error] 	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
[error] 	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
[error] 	at scala.collection.immutable.List.foreach(List.scala:392)
[error] 	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
[error] 	at scala.collection.immutable.List.map(List.scala:296)
[error] 	at firrtl.ir.Block.mapStmt(IR.scala:285)
[error] 	at firrtl.Mappers$StmtMagnet$$anon$1.map(Mappers.scala:16)
[error] 	at firrtl.Mappers$StmtMap$.map$extension(Mappers.scala:33)
[error] 	at firrtl.passes.InferTypes$.firrtl$passes$InferTypes$$infer_types_s$1(InferTypes.scala:59)
[error] 	at firrtl.passes.InferTypes$$anonfun$firrtl$passes$InferTypes$$infer_types_s$1$5.apply(InferTypes.scala:59)
[error] 	at firrtl.passes.InferTypes$$anonfun$firrtl$passes$InferTypes$$infer_types_s$1$5.apply(InferTypes.scala:59)
[error] 	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
[error] 	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
[error] 	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
[error] 	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
[error] 	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
[error] 	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
[error] 	at firrtl.ir.Block.mapStmt(IR.scala:285)
[error] 	at firrtl.Mappers$StmtMagnet$$anon$1.map(Mappers.scala:16)
[error] 	at firrtl.Mappers$StmtMap$.map$extension(Mappers.scala:33)
[error] 	at firrtl.passes.InferTypes$.firrtl$passes$InferTypes$$infer_types_s$1(InferTypes.scala:59)
[error] 	at firrtl.passes.InferTypes$$anonfun$firrtl$passes$InferTypes$$infer_types_s$1$5.apply(InferTypes.scala:59)
[error] 	at firrtl.passes.InferTypes$$anonfun$firrtl$passes$InferTypes$$infer_types_s$1$5.apply(InferTypes.scala:59)
[error] 	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
[error] 	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
[error] 	at scala.collection.immutable.List.foreach(List.scala:392)
[error] 	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
[error] 	at scala.collection.immutable.List.map(List.scala:296)
[error] 	at firrtl.ir.Block.mapStmt(IR.scala:285)
[error] 	at firrtl.Mappers$StmtMagnet$$anon$1.map(Mappers.scala:16)
[error] 	at firrtl.Mappers$StmtMap$.map$extension(Mappers.scala:33)
[error] 	at firrtl.passes.InferTypes$.firrtl$passes$InferTypes$$infer_types_s$1(InferTypes.scala:59)
[error] 	at firrtl.passes.InferTypes$$anonfun$firrtl$passes$InferTypes$$infer_types_s$1$5.apply(InferTypes.scala:59)
[error] 	at firrtl.passes.InferTypes$$anonfun$firrtl$passes$InferTypes$$infer_types_s$1$5.apply(InferTypes.scala:59)
[error] 	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
[error] 	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
[error] 	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
[error] 	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
[error] 	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
[error] 	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
[error] 	at firrtl.ir.Block.mapStmt(IR.scala:285)
[error] 	at firrtl.Mappers$StmtMagnet$$anon$1.map(Mappers.scala:16)
[error] 	at firrtl.Mappers$StmtMap$.map$extension(Mappers.scala:33)
[error] 	at firrtl.passes.InferTypes$.firrtl$passes$InferTypes$$infer_types_s$1(InferTypes.scala:59)
[error] 	at firrtl.passes.InferTypes$$anonfun$firrtl$passes$InferTypes$$infer_types_s$1$5.apply(InferTypes.scala:59)
[error] 	at firrtl.passes.InferTypes$$anonfun$firrtl$passes$InferTypes$$infer_types_s$1$5.apply(InferTypes.scala:59)
[error] 	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
[error] 	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
[error] 	at scala.collection.immutable.List.foreach(List.scala:392)
[error] 	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
[error] 	at scala.collection.immutable.List.map(List.scala:296)
[error] 	at firrtl.ir.Block.mapStmt(IR.scala:285)
[error] 	at firrtl.Mappers$StmtMagnet$$anon$1.map(Mappers.scala:16)
[error] 	at firrtl.Mappers$StmtMap$.map$extension(Mappers.scala:33)
[error] 	at firrtl.passes.InferTypes$.firrtl$passes$InferTypes$$infer_types_s$1(InferTypes.scala:59)
[error] 	at firrtl.passes.InferTypes$$anonfun$firrtl$passes$InferTypes$$infer_types$1$3.apply(InferTypes.scala:70)
[error] 	at firrtl.passes.InferTypes$$anonfun$firrtl$passes$InferTypes$$infer_types$1$3.apply(InferTypes.scala:70)
[error] 	at firrtl.ir.Module.mapStmt(IR.scala:542)
[error] 	at firrtl.Mappers$ModuleMagnet$$anon$12.map(Mappers.scala:93)
[error] 	at firrtl.Mappers$ModuleMap$.map$extension(Mappers.scala:106)
[error] 	at firrtl.passes.InferTypes$.firrtl$passes$InferTypes$$infer_types$1(InferTypes.scala:70)
[error] 	at firrtl.passes.InferTypes$$anonfun$6.apply(InferTypes.scala:73)
[error] 	at firrtl.passes.InferTypes$$anonfun$6.apply(InferTypes.scala:73)
[error] 	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
[error] 	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
[error] 	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
[error] 	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
[error] 	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
[error] 	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
[error] 	at firrtl.passes.InferTypes$.run(InferTypes.scala:73)
[error] 	at firrtl.passes.Pass$class.execute(Passes.scala:24)
[error] 	at firrtl.passes.InferTypes$.execute(InferTypes.scala:10)
[error] 	at firrtl.Transform$$anonfun$2.apply(Compiler.scala:257)
[error] 	at firrtl.Transform$$anonfun$2.apply(Compiler.scala:257)
[error] 	at firrtl.Utils$.time(Utils.scala:182)
[error] 	at firrtl.Transform.runTransform(Compiler.scala:257)
[error] 	at firrtl.SeqTransformBased$$anonfun$runTransforms$1.apply(Compiler.scala:309)
[error] 	at firrtl.SeqTransformBased$$anonfun$runTransforms$1.apply(Compiler.scala:309)
[error] 	at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
[error] 	at scala.collection.immutable.List.foldLeft(List.scala:84)
[error] 	at firrtl.SeqTransformBased$class.runTransforms(Compiler.scala:309)
[error] 	at firrtl.SeqTransform.runTransforms(Compiler.scala:313)
[error] 	at firrtl.SeqTransform.execute(Compiler.scala:319)
[error] 	at firrtl.Transform$$anonfun$2.apply(Compiler.scala:257)
[error] 	at firrtl.Transform$$anonfun$2.apply(Compiler.scala:257)
[error] 	at firrtl.Utils$.time(Utils.scala:182)
[error] 	at firrtl.Transform.runTransform(Compiler.scala:257)
[error] 	at firrtl.Compiler$$anonfun$7$$anonfun$apply$8.apply(Compiler.scala:471)
[error] 	at firrtl.Compiler$$anonfun$7$$anonfun$apply$8.apply(Compiler.scala:471)
[error] 	at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
[error] 	at scala.collection.immutable.List.foldLeft(List.scala:84)
[error] 	at firrtl.Compiler$$anonfun$7.apply(Compiler.scala:471)
[error] 	at firrtl.Compiler$$anonfun$7.apply(Compiler.scala:471)
[error] 	at firrtl.Utils$.time(Utils.scala:182)
[error] 	at firrtl.Compiler$class.compile(Compiler.scala:470)
[error] 	at firrtl.VerilogCompiler.compile(LoweringCompilers.scala:149)
[error] 	at firrtl.Driver$$anonfun$execute$1.apply(Driver.scala:225)
[error] 	at firrtl.Driver$$anonfun$execute$1.apply(Driver.scala:209)
[error] 	at logger.Logger$$anonfun$makeScope$1.apply(Logger.scala:138)
[error] 	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
[error] 	at logger.Logger$.makeScope(Logger.scala:136)
[error] 	at firrtl.Driver$.execute(Driver.scala:209)
[error] 	at chisel3.Driver$.execute(Driver.scala:182)
[error] 	at chisel3.Driver$.execute(Driver.scala:202)
[error] 	at Main$.delayedEndpoint$Main$1(Top.scala:130)
[error] 	at Main$delayedInit$body.apply(Top.scala:129)
[error] 	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
[error] 	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
[error] 	at scala.App$$anonfun$main$1.apply(App.scala:76)
[error] 	at scala.App$$anonfun$main$1.apply(App.scala:76)
[error] 	at scala.collection.immutable.List.foreach(List.scala:392)
[error] 	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
[error] 	at scala.App$class.main(App.scala:76)
[error] 	at Main$.main(Top.scala:129)
[error] 	at Main.main(Top.scala)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)
[error] 	at sbt.Run.invokeMain(Run.scala:93)
[error] 	at sbt.Run.run0(Run.scala:87)
[error] 	at sbt.Run.execute$1(Run.scala:65)
[error] 	at sbt.Run.$anonfun$run$4(Run.scala:77)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] 	at sbt.util.InterfaceUtil$$anon$1.get(InterfaceUtil.scala:10)
[error] 	at sbt.TrapExit$App.run(TrapExit.scala:252)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] java.lang.RuntimeException: Nonzero exit code: 1
[error] 	at sbt.Run$.executeTrapExit(Run.scala:124)
[error] 	at sbt.Run.run(Run.scala:77)
[error] 	at sbt.Defaults$.$anonfun$bgRunMainTask$6(Defaults.scala:1147)
[error] 	at sbt.Defaults$.$anonfun$bgRunMainTask$6$adapted(Defaults.scala:1142)
[error] 	at sbt.internal.BackgroundThreadPool.$anonfun$run$1(DefaultBackgroundJobService.scala:366)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] 	at scala.util.Try$.apply(Try.scala:209)
[error] 	at sbt.internal.BackgroundThreadPool$BackgroundRunnable.run(DefaultBackgroundJobService.scala:289)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (Compile / runMain) Nonzero exit code: 1
[error] Total time: 8 s, completed Dec 15, 2018 8:42:57 AM
```

**Comment by maloneymr** [comment]
The offending line seems to be:

```
        io.hs := !(
          sync >= horizontalFrontPorch &&
          sync < horizontalBlanking - horizontalBackPorch
        )
```

It's not clear to me why this is causing issues, since it should be allowed under Chisel's "last assignment statement wins" rule.

Any clarity to this issue (bearing in mind I'm a beginner!) would still be appreciated!

**Comment by seldridge** [comment]
Thanks for figuring out the offending line. I've stripped this down to a further MWE below:

```scala
package examples

import chisel3._
import chisel3.experimental.RawModule

import org.scalatest.{FlatSpec, Matchers}

class f973 extends FlatSpec with Matchers {

  class Foo extends RawModule {
    val x = Wire(Bool())
    when (true.B) { x := true.B }
    x := true.B
  }

  class Bar extends RawModule {
    val x = WireInit(false.B)
    when (true.B) { x := true.B }
    x := true.B
  }

  behavior of "f973 issue"

  it should "work on a Wire" in {
    chisel3.Driver.execute(Array("-X", "middle"), () => new Foo) /* This is failing */
  }

  it should "work on a WireInit" in {
    chisel3.Driver.execute(Array("-X", "middle"), () => new Bar) /* This works */
  }

}
```

The issue appears to be that `passes.ExpandWhens` will emit `WVoid` for situations where it can't resolve a default value. However, you've exposed a situation where the `when` block should be entirely removed by last connect semantics and that `WVoid` doesn't matter.

Before `ExpandWhens` the circuit is:
```
Circuit:
circuit f973Foo :
  module f973Foo :
  
    wire x : UInt<1> @[f973.scala 11:17]
    when UInt<1>("h1") : @[f973.scala 12:19]
      x <= UInt<1>("h0") @[f973.scala 12:23]
    x <= UInt<1>("h1") @[f973.scala 13:7]
```

After `ExpandWhens` the circuit is:
```
Circuit:
circuit f973Foo :
  module f973Foo :
  
    wire x : UInt<1> @[f973.scala 11:17]
    node _GEN_0 = mux(UInt<1>("h1"), UInt<1>("h0"), VOID) @[f973.scala 12:19]
    x <= UInt<1>("h1") @[f973.scala 12:23 f973.scala 13:7]
```

This then fails `ResolveKinds`.

@maloneymr: Your code, while entirely legal, should likely not be specifying a default value _last_. Last connect semantics mean that the assignment to `io.hs` in your `when` block will always be overridden by the default value you specify at the end. You likely intended to specify this before everything else. If you do that, then your code should compile. Unfortunately, this appears to be exposing a bug in FIRRTL...
